### ISSUE TITLE
Manage context  with `with`

### ISSUE THREAD

**Issue by fractalliter** [M91skr/photo_editor#1]
Opening a file and its context should be manages via `with` like bellow:
```python
with Image.open(filename) as im:
      img.save(file_path)
```
instead of
https://github.com/M91skr/photo_editor/blob/70b9de6ed546e0897b5e7e749f55fa0ac30c410f/main.py#L37C18-L37C18

**Comment by M91skr** [comment]
The declaration of the problem was correct. In the program with the problem, the files were opened but not closed. And this made me leave a lot of open files when running my program.
Thank you very much and I fixed the problem in #3
